backend_repo_url: "https://github.com/pravinmishraaws/book-review-app.git"
backend_app_port: 3001
db_host: "128.24.55.60"
db_user: "mysqladmin"
db_password: "DevSecureDBPassword123!"
db_name: "book_review_db"
jwt_secret: "your_jwt_secret"
allowed_origins: "http://172.177.100.226:3000"
